### PR TITLE
Fixed bug where LoRA stopped working when HiRes was enabled.

### PR DESCRIPTION
**Pull request by nihedon**
#167 

Hiresが有効のときLoRAが効かなくなるバグを修正しました。
※新しく作り直したlbwf関数がLoRAの辞書に対して破壊的な作りになっていたことが原因だったのでdeepcopyを使用し呼び出し元に影響がないようにしました。

Fixed a bug where LoRA would stop working when Hires was enabled.
Note: The issue was caused by the newly reworked lbwf function destructively modifying the LoRA dictionary, so I used deepcopy to prevent any impact on the original data.

### CODE REVIEW

**Comment by nihedon** [comment]
テスト不足で正しく動作していないことが発覚したためクローズします。

**Comment by nihedon** [comment]
前回の修正（deepcopy）では**LoRAブロック指定自体が効かなく**なっていました。
deepcopyを使用するのではなく、必要なオブジェクトの場合は削除しない用に修正しました。

**Comment by ddoscv** [comment]
@nihedon Hi, may I know what version of Forge are you using? I have [f1.0.2-v1.10.1RC-latest-693-gdee9105a](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/dee9105a66baca36dab6f5949ecec6abdc1bdc0f) but I am still getting the error. Sorry I am confused and know nothing about github and coding/programming.

**Comment by nihedon** [comment]
@ddoscv 
Sorry, the version I have implemented is based on Illyasviel's version of Forge.
As far as I know, there are currently four types of UIs:
- A1111
- Old Forge (versions before August)
- New Forge (versions after August)
- reForge
- SD-Next

Each of these UIs is being developed on its own path, and it's becoming difficult to make them all compatible...
The one I supported is the New Forge, so I cannot guarantee that it will work with reForge.

I understand that many users are also using reForge, so I would like to support it if possible, but if it complicates the logic too much, I may have to give up on it.

**Comment by hako-mikan** [comment]
ありがとうございます。
手が回らないので本当に助かります。

**Comment by ddoscv** [comment]
@nihedon Hi, thank you for the reply. I honestly don't know what version of reForge I was using before I accidentally updated my extensions yesterday. After that, I did "git pull" via editing the webui-user.bat hoping that maybe the LBW extension would work, but sadly it didn't.

Thankfully it seems I have made a backup of both the extension and version a few months ago so I just used that. I used to have hako-mikan's LBW, I thought once I restore my backup it would revert into that. But when I checked my extensions, it seems the one installed there is the fork you made. Also after restoring the backup, this is now the version of webui I have " f1.0.2-v1.10.1RC-latest-691-g37223711". I don't know if that's the old or new or reForge honestly. But I don't get the error anymore. I normally don't update anything, it's just I accidentally clicked on "check for updates" instead of "reload UI". Well, it works now, I guess it's no use figuring this out haha.

Thank you so much for this extension ^^

**Pull request merged**
